# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b9ae1c58e755b0e6421194316efe7bc4a30774e5ec294ba32e3fd2f7a2de39d13e10fd583716cf0bda7ffc03995fce675ebdb69ade5e4dd4439eef6440226f5a

test:
  secret_key_base: fcb00fe3a958beb375a99d4dee227ac84076a1390f3558bb9dcf09825ef5b353102ed2a2140365febf59c3ca4488c44c9ed654c289b95c15883798de67daa20a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
